"""Agregar tabla de pasos para el roadmap

Revision ID: d6586d171c26
Revises: 0f99bbdafcf7
Create Date: 2024-10-20 00:26:55.394365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6586d171c26'
down_revision = '0f99bbdafcf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.alter_column('problema',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.alter_column('problema',
               existing_type=sa.TEXT(),
               nullable=True)

    # Eliminar la tabla 'step'
    op.drop_table('step')
    # ### end Alembic commands ###
